adding .goreleaser.yml
percona/rds_exporter pull request #72
Opened 2021-12-08 16:09 UTC by maxknee

Adding a `.goreleaser.yml` similarly found `mongodb_exporter`

2021-12-08 16:09 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/rds_exporter?pullRequest=72) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/rds_exporter?pullRequest=72) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/rds_exporter?pullRequest=72) it.</sub>

2021-12-08 16:12 UTC, denisok commented
@maxknee thanks for contribution! looks like you are missing the new line at the end of the file.

Also check this: https://github.com/percona/mongodb_exporter/pull/392  probably would land soon.

2021-12-08 16:32 UTC, maxknee commented
> @maxknee thanks for contribution! looks like you are missing the new line at the end of the file.
> 
> Also check this: [percona/mongodb_exporter#392](https://github.com/percona/mongodb_exporter/pull/392) probably would land soon.

do we want to roll this in OR add it after this is merged? Happy to do either

2021-12-08 16:49 UTC, denisok commented
> > @maxknee thanks for contribution! looks like you are missing the new line at the end of the file.
> > Also check this: [percona/mongodb_exporter#392](https://github.com/percona/mongodb_exporter/pull/392) probably would land soon.
> 
> do we want to roll this in OR add it after this is merged? Happy to do either

as you would like. just test that it works.

2021-12-08 16:50 UTC, maxknee commented
> 

Would prefer to merge, then work on releasing it as a package. 
Need the `aws_iam_role` feature sooner

2021-12-08 16:58 UTC, denisok commented on .goreleaser.yml
> +
```suggestion

```

2021-12-08 17:13 UTC, denisok commented
ok. could you please also add release action then?
https://github.com/percona/mongodb_exporter/blob/main/.github/workflows/release.yml

and please remove docker container as for now, as creating new project in docker hub would take some time and we didn't plan that yet.

or you can try to change it to push to github and lets see if it works: `ghcr.io/` : 
```
  image_templates:
  - "ghcr.io/percona/rds_exporter:{{.Major}}.{{.Minor}}"
  - "ghcr.io/percona/rds_exporter:{{.Version}}"
  ```

2021-12-10 14:48 UTC, denisok commented
@maxknee it is and error from Docker file when it tries to build it:
https://github.com/percona/rds_exporter/blob/main/Dockerfile#L9

For new pipeline that is unnecessary and probably doesn't work because there are no sources there (or they are in different location).

You probably need to add new docker file and specify it in the goreleaser:
`dockerfile: Dockerfile.release`

Or rework existing Dockerfile (btw pay attention to the yml, it should be in the container on that path)

2021-12-10 20:18 UTC, denisok requested changes

2021-12-10 20:18 UTC, denisok commented on Dockerfile
> -FROM alpine:latest
looks like you also modified old Docker file. Please leave it untouched.

2021-12-10 20:19 UTC, denisok commented on Dockerfile
> -FROM alpine:latest
oops, some strange cached changes

2021-12-10 20:23 UTC, denisok approved these changes

2021-12-10 22:57 UTC, percona-csalguero approved these changes

2021-12-13 09:16 UTC, merged

2021-12-13 09:29 UTC, yonahd commented
@denisok I don't think a release will be able to be created without the tests passing

2021-12-13 11:06 UTC, denisok commented
@yonahd those test failed because they couldn't run from the forked repo. We would run test one way or another.

2021-12-13 16:05 UTC, yonahd commented
@denisok isn't the goal to create a new release?

2021-12-14 09:44 UTC, denisok commented
@yonahd didn't get you. Yes the goal is to create new release. And thus tests need to pass.
https://github.com/percona/rds_exporter/issues/74